PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL   
);

DROP TABLE IF EXISTS TAGS;
CREATE TABLE TAGS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL   
);

DROP TABLE IF EXISTS STATUS_FILES;
CREATE TABLE STATUS_FILES(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL   
);

DROP TABLE IF EXISTS STRATEGY_CHUNKS;
CREATE TABLE STRATEGY_CHUNKS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL   
);


DROP TABLE IF EXISTS DOCUMENTS;
CREATE TABLE DOCUMENTS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    name_file TEXT NOT NULL,
    size INTEGER NOT NULL,
    mime_type TEXT NOT NULL,
    tags_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (tags_id) REFERENCES TAGS(id),
    FOREIGN KEY (status_id) REFERENCES STATUS_FILES(id)
);

DROP TABLE IF EXISTS CHUNKS;
CREATE TABLE CHUNKS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    order_chunk INTEGER NOT NULL,
    strategy_chunk_id INTEGER NULL,
    token_count INTEGER  NULL,
    overlap_token INTEGER  NULL,
    metadata JSON NULL, 
    is_convert_embeded BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(id),
    FOREIGN KEY (strategy_chunk_id) REFERENCES STRATEGY_CHUNKS(id)
);

DROP TABLE IF EXISTS QUESTIONS;
CREATE TABLE QUESTIONS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tags_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (tags_id) REFERENCES TAGS(id)
);

DROP TABLE IF EXISTS EMBEDDINGS;
CREATE VIRTUAL TABLE EMBEDDINGS USING vec0(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chunk_id INTEGER  NULL,
    question_id INTEGER  NULL,
    embedding float[4096] distance_metric=cosine
);

DROP TABLE IF EXISTS evaluations;
CREATE TABLE evaluations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER NOT NULL,
    strategy_chunk INTEGER NOT NULL,
    tags_id INTEGER NOT NULL,
    mime_type_file TEXT NOT NULL,
    total_chunks INTEGER NOT NULL,
    avg_tokens REAL NOT NULL,
    total_token REAL NOT NULL,
    evalutation_for_row JSON NULL,
    total_evaluation REAL NOT NULL,
    score REAL NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(id) ON DELETE CASCADE,
    FOREIGN KEY (strategy_chunk) REFERENCES STRATEGY_CHUNKS(id) ON DELETE CASCADE,
    FOREIGN KEY (tags_id) REFERENCES TAGS(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    metadata JSON NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);

DROP TABLE IF EXISTS FAILED_JOBS;
CREATE TABLE FAILED_JOBS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL,
    exception TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (job_id) REFERENCES JOBS(id) ON DELETE CASCADE
);